// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkx-t5l2FrV-ZC0apxlCd-YzzO-U30vs',
    appId: '1:637326714487:web:6635412b5ef81420524872',
    messagingSenderId: '637326714487',
    projectId: 'fir-task-1-36038',
    authDomain: 'fir-task-1-36038.firebaseapp.com',
    storageBucket: 'fir-task-1-36038.firebasestorage.app',
    measurementId: 'G-11K2M4TEEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlXbcY1sSecGWWc02mOxiBvPbiE4JlUdo',
    appId: '1:637326714487:android:519b47a0c3436c1d524872',
    messagingSenderId: '637326714487',
    projectId: 'fir-task-1-36038',
    storageBucket: 'fir-task-1-36038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15TuXP9QpiqcgVOnMZ7Ir1v8v01lwlxw',
    appId: '1:637326714487:ios:e6fad1513e159965524872',
    messagingSenderId: '637326714487',
    projectId: 'fir-task-1-36038',
    storageBucket: 'fir-task-1-36038.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC15TuXP9QpiqcgVOnMZ7Ir1v8v01lwlxw',
    appId: '1:637326714487:ios:e6fad1513e159965524872',
    messagingSenderId: '637326714487',
    projectId: 'fir-task-1-36038',
    storageBucket: 'fir-task-1-36038.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGkx-t5l2FrV-ZC0apxlCd-YzzO-U30vs',
    appId: '1:637326714487:web:92920ae5be020fd0524872',
    messagingSenderId: '637326714487',
    projectId: 'fir-task-1-36038',
    authDomain: 'fir-task-1-36038.firebaseapp.com',
    storageBucket: 'fir-task-1-36038.firebasestorage.app',
    measurementId: 'G-3664C69ELL',
  );
}
